id: audit_log_file_size_configure
title: "Configure Audit Log File Size"
discussion: |
  Sets a maximum file size for each log file. Increasing the file size of logs facilitates management of the audit logging subsystem.
check: |
  /usr/bin/awk -F: '/filesz/{print $2}' /etc/security/audit_control
result:
  string: 80M
fix: |
  [source,bash]
  ----
  /usr/bin/sed -i.bak 's/^filesz.*/filesz:80M/' /etc/security/audit_control; /usr/sbin/audit -s
  ----
references:
  cce:
    - n/a
  cci:
    - n/a
  800-53r4:
    - n/a
  srg:
    - n/a
  disa_stig:
    - n/a
  800-92:
    - 2.3.2
    - 3.2
    - 5.1.2
macOS:
  - "11.0"
tags:
  - 800-179_standalone
  - 800-179_managed
  - 800-179_sslf
  - preliminary
mobileconfig: false
mobileconfig_info:
